# Generated by Django 4.2.4 on 2023-11-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user_id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="ID Телеграм"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=25, verbose_name="Имя Телеграм"),
                ),
                ("first_name", models.CharField(max_length=25, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=25, verbose_name="Фамилия")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "is_subscribed",
                    models.BooleanField(
                        default=False, verbose_name="Подписан на рассылку"
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Когда зарегестрирован"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["-registered_at"],
            },
        ),
    ]
